Adds Brake Fix, Buy, and Dinghy Slide running sounds.
OpenRCT2/OpenSoundEffects pull request #12
Opened 2022-10-09 23:09 UTC by Generalcamo

This PR also adds an attributions file. Format is not finalized (this is heavily based on OpenTTD's OpenSFX's equivalent file), but I needed to get this here to properly attribute these sounds (as the CC BY license requires this).

2025-01-16 00:00 UTC, Generalcamo commented
I have rebased this to account for the changes made to this project since I made this commit.

2025-04-11 13:20 UTC, karst commented
I will look at this again tonight.
I am willing to merge this if everything checks out.

One thing I will say though, since these are soundfx from a royalty free library, if anyone decides to make their own recordings for these, they might overwrite these.

Should've probably done this a while back. Sorry about that.

2025-04-13 09:19 UTC, karst requested changes
I have a few comments on the provided files.
If you need any help with balancing I'll gladly do that for you.

The samples overview in the json:
``` 
           "samples": [
                "$[0..3]",
                "samples/click_in.flac",
                "samples/click_out.flac",
                "$[0..3]",
                "samples/scream_el_zadra.flac",
                "$[0..2]",
                "samples/buy1.flac",
                "$[0..3]",
                "samples/train_whistle_1_cp_railroad.flac",
                "samples/train_whistle_depart_cp_railroad.flac",
                "$[0..1]",
                "samples/hydrolics_wh_lost_gravity.flac",
                "samples/hydrolics_wh_space_shot.flac",
                "$[0..3]",
                "samples/rain.flac",
                "samples/thunder_3.flac",
                "samples/thunder_4.flac",
                "$[0..0]",
                "samples/dinghy_slide.flac",
                "samples/pop.flac",
                "SoundFX/brake_fix.flac",
                "$[0..0]",
                "samples/flush.flac",
                "samples/click_in.flac",
                "$[0..0]",
                "samples/news.flac",
                "$[0..7]",
                "samples/hydrolics_mm_ninja.flac",
                "samples/hydrolics_el_abyssus.flac",
                "samples/error.flac",
                "samples/hydrolics_tow_truck.flac",
                "samples/hyper_rc_lift_cp_magnum_xl_200.flac",
                "samples/wood_rc_lift_cp_blue_streak.flac",
                "$[0..1]",
                "samples/bm_rc_lift_cp_rougarou.flac",
                "samples/bm_rc_roar_cp_rougarou_pa_oziris.flac",
                "$[0..4]",
                "samples/crowd.flac"
            ]
```

2025-04-13 09:19 UTC, karst commented on openrct2.sound/openrct2.sound.json
> +                "$[0..2]",
Thisone should be `0..1`, you went from 7 samples to 8 :)

2025-04-13 09:19 UTC, karst commented on openrct2.sound/openrct2.sound.json
> +                "SoundFX/brake_fix.flac"
this is missing a comma, invaliidating the json file

2025-04-13 09:19 UTC, karst commented on openrct2.sound/openrct2.sound.json
> +                "samples/buy1.flac",
The name here is not accurate with the name of the included sample.

2025-04-13 09:19 UTC, karst commented on openrct2.sound/samples/cash1.flac
I like this sound, but it feels very cursed from the original haha. It's a tad loud, would probably be good to turn it down a bit.

2025-04-13 09:19 UTC, karst commented on openrct2.sound/samples/dinghy_slide.flac
This sounds incredible in game. It feels super nostalgic for some reason. I would also turn this sound down a tad for balancing.

2025-04-13 09:19 UTC, karst commented on openrct2.sound/samples/brake_fix.flac
I don't remember how to trigger this sound. LMK how I can do this so I can test this :)

2025-04-18 07:39 UTC, Gymnasiast commented on openrct2.sound/samples/brake_fix.flac
You need to cause a brakes failure, then let a mechanic fix it. He’ll hit the brakes with a mallet, at which point this sound will be played.

2025-07-23 15:10 UTC, karst approved these changes

2025-07-23 15:35 UTC, karst commented
Everything's good now. Sorry for taking so long.

2025-07-23 15:36 UTC, merged